export { default as NotFoundPage } from "./404";
export { default as ProfilePage } from "./profile";
export { default as ProjectPage } from "./project";
export { default as FinancePage } from "./finance";
export { default as Academic } from "./academic";
export { default as Analytics } from "./analytics";
export { default as Crypto } from "./crypto";
export { default as Contacts } from "./contacts";
export { default as Chat } from "./chat";
